---
#------------------------------------------------------------------------------
# Synchronizes the site files locally to the remote nginx server(s)
#------------------------------------------------------------------------------

- name: Sync nginx site files
  hosts: www          # use with the *aws_ec2.yaml inventory plugin
  gather_facts: yes   # required for `ansible_date_time`
  vars_files:
    vars.yaml
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: "{{ ssh_keypair_private_file }}"
    # ansible_ssh_pass=password
    # ansible_connection=ssh
  tasks:

  # - name: Sync nginx site contents
  #   become: yes
  #   ansible.builtin.copy:
  #     src: ./files/static_site/
  #     dest: /opt/static_site

  - name: Sync nginx site contents
    delegate_to: localhost
    become: yes
    ansible.posix.synchronize:
      src: ./files/static_site     # relative path; no trailing /
      dest: /opt                   # absolute path; no trailing /


...