---
# -----------------------------------------------------------------------------
# NGINX Installation and Configuration Resources :
# - http://nginx.org/en/linux_packages.html
# - https://www.nginx.com/resources/wiki/start/
# - https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
# - https://wiki.debian.org/Nginx/DirectoryStructure
# -----------------------------------------------------------------------------


  - name: Install nginx
    become: yes
    ansible.builtin.apt:
      state: latest     # absent | build-dep | latest | present | fixed
      pkg:
      - nginx
      update_cache: yes
      autoremove: yes
      autoclean: yes
      cache_valid_time: 86400   # 1 day


  - name: Copy the nginx config
    become: yes
    ansible.builtin.copy:
      src: ./files/nginx.cfg
      dest: /etc/nginx/sites-enabled/nginx.cfg


  - name: Delete `/etc/nginx/sites-available/default` config
    become: yes
    ansible.builtin.file:
      state: absent
      path: /etc/nginx/sites-available/default


  - name: Delete `/etc/nginx/sites-enabled/default` config
    become: yes
    ansible.builtin.file:
      state: absent
      path: /etc/nginx/sites-enabled/default


  - name: Copy the content of the web site
    become: yes
    ansible.builtin.copy:
      src: ./files/static_site/
      dest: /opt/static_site


  - name: Start nginx
    become: yes
    ansible.builtin.service:
      name: nginx
      enabled: yes
      state: started


...